name: test-all-modules

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  update-documentation:
    name: "Update Terraform Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update Documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          working-dir: modules/vnet
          output-file: README.md
          output-method: inject
          git-push: "true"      
      # - name: Commit and Push
      #   # uses: stefanzweifel/git-auto-commit-action@v5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.REPO_GITHUB_TOKEN }}
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "derek.ashmore@dvtconsulting.com"
      #     git add .
      #     git commit -m "Update README.md"
      #     git push

  test-modules:
    name: "Module Test Suite"
    needs: update-documentation
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.6.1
      MODULE_DIR: modules
    steps:
    # - name: Check out code
    #   uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{env.TERRAFORM_VERSION}}
    - name: Test Vnet
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        cd ${{env.MODULE_DIR}}/vnet
        terraform init
        terraform test



