name: test-all-modules

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  update-documentation:
    name: "Update Terraform Documentation"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Update Documentation
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          output-file: README.md
          output-method: inject
          atlantis-file: terraform_folders.yml
          git-push: "true"      

  test-modules:
    name: "Module Test Suite"
    needs: update-documentation
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.6.1
      MODULE_DIR: modules
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{env.TERRAFORM_VERSION}}
    - name: Test Vnet
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        cd ${{env.MODULE_DIR}}/vnet
        terraform init
        terraform test



