name: update-documentation

on:
    pull_request:
        branches:
        - main

jobs:
    update-documentation:
        name: "Update Terraform Documentation"
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3
          with: 
            ref: ${{ github.event.pull_request.head.ref }}
        - name: Update Documentation
          uses: terraform-docs/gh-actions@v1.0.0
          with:
            output-file: README.md
            output-method: inject
            atlantis-file: terraform_folders.yml
            git-push: "true"      